version: '3'
services:
  node:
    build:
      context: .
      dockerfile: 'Dockerfile'
    container_name: 'create-card'
    tty: true
    restart: always
    volumes:
      - ./:/root/create-card
    working_dir: '/root/create-card'