version: '3'
services:
  node:
    build:
      context: .
      dockerfile: 'Dockerfile'
    container_name: 'react_test'
    tty: true
    restart: always
    volumes:
      - ./:/root/react_test
    working_dir: '/root/react_test'